version: "3.6"
services:
    nginx:
      build:
        context: .
        dockerfile: Dockerfile
      ports:
          - 1180:80
          - 11443:443
      volumes:
          - ./config:/home/spnego/config
          - ./config/nginx.conf:/etc/nginx/nginx.conf